name: Manual workflow
on:
  workflow_dispatch:
    inputs:
      name:
        # Description to be shown in the UI instead of 'name'
        description: "Person to greet"
        # Default value if no value is explicitly provided
        default: "Octocat"
        # Input has to be provided for the workflow to run
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Send greeting
        run: echo "Hello ${{ github.event.inputs.name }}"

  dispatch:
    runs-on: ubuntu-latest
    steps:
      # this is the old way of triggering repo workflow using github actions api
      # - run: |
      #     curl -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
      #       -H "Accept: application/vnd.github.everest-preview+json" \
      #       -H "Content-Type: application/json" \
      #       https://api.github.com/repos/docker-sstc/docker-notify/actions/workflows/main.yml/dispatches \
      #       --data '{"ref": "master"}'
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'RijoyChowdhury',
              repo: 'example-event-dispatcher-workflows',
              workflow_id: 'ping.yml',
              ref: 'main',
              inputs: {
                name: '${{ github.event.inputs.name }}'
              }
            })
